<?php

namespace app\module\api\controllers;

use app\models\Merchant;
use app\models\User;
use yii\web\Controller;
use yii\web\Response;

/**
 * Default controller for the `api` module
 */
class V1Controller extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionUsers($token = null)
    {
        /** @var User $user */
        $user = User::find()->where(['token' => $token])->one();

        $response = ['user' => null];

        if ($user) {
            $response['user'] = [
                'name' => $user->name,
                'email' => $user->email,
                'created' => $user->created
            ];
        }

        return json_encode($response);
    }

    public function actionMerchants($id = null)
    {
        /** @var Merchant $merchant */
        $merchant = Merchant::find()->where($id)->one();

        $response = ['merchant' => null];

        if ($merchant) {
            $response['merchant'] = [
                'name' => $merchant->name,
                'description' => $merchant->description
            ];
        }

        return json_encode($response);
    }
}
