<?php

namespace app\module\api\controllers;

use app\models\Coupon;
use app\models\Merchant;
use app\models\User;
use yii\web\Controller;
use yii\web\Response;

/**
 * Default controller for the `api` module
 */
class V1Controller extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionUsers($token = null)
    {
        /** @var User $user */
        $user = User::find()->where(['token' => $token])->one();

        $response = ['user' => null];

        if ($user) {
            $response['user'] = [
                'name' => $user->name,
                'email' => $user->email,
                'created' => $user->created
            ];
        }

        return json_encode($response);
    }

    public function actionMerchants($id = null)
    {
        /** @var Merchant $merchant */
        $merchant = Merchant::find()->where($id)->one();

        $response = ['merchant' => null];

        if ($merchant) {
            $response['merchant'] = [
                'name' => $merchant->name,
                'description' => $merchant->description
            ];
        }

        return json_encode($response);
    }

    public function actionUserCoupons($user_id)
    {
        /** @var User $user */
        $user = User::find()->where(['id' => $user_id])->one();

        $response = ['coupons' => $this->getCouponJson($user)];

        return json_encode($response);
    }

    public function actionMerchantCoupons($merchant_id)
    {
        /** @var Merchant $merchant */
        $merchant = Merchant::find()->where(['id' => $merchant_id])->one();

        $response = ['coupons' => $this->getCouponJson($merchant)];

        return json_encode($response);
    }

    /**
     * @param Merchant | User $model
     * @return array
     */
    private function getCouponJson($model)
    {
        $list = [];
        if ($model && $coupons = $model->getCoupons()->all()) {
            /** @var Coupon $coupon */
            foreach ($coupons as $coupon) {
                $list[] = [
                    'title' => $coupon->title,
                    'code' => $coupon->code
                ];
            }
        }
        return $list;
    }
}
