<?php

namespace app\module\api\controllers;

use app\models\Merchant;
use app\models\MerchantCoupon;
use app\models\User;
use app\models\UserCoupon;
use yii\web\Controller;


class V1Controller extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionUsers($token = null)
    {
        /** @var User $user */
        $user = User::find()->where(['token' => $token])->one();

        $response = ['user' => null];

        if ($user) {
            $response['user'] = [
                'name' => $user->name,
                'email' => $user->email,
                'created' => $user->created
            ];
        }

        return json_encode($response);
    }

    public function actionMerchants($id = null)
    {
        /** @var Merchant $merchant */
        $merchant = Merchant::find()->where(['id' => $id])->one();

        $response = ['merchant' => null];

        if ($merchant) {
            $response['merchant'] = [
                'name' => $merchant->name,
                'description' => $merchant->description
            ];
        }

        return json_encode($response);
    }

    public function actionUserCoupons($user_id)
    {
        $coupons = UserCoupon::find()->where(['user_id' => $user_id])->all();

        $response = ['coupons' => $this->getCouponJson($coupons)];

        return json_encode($response);
    }

    public function actionMerchantCoupons($merchant_id)
    {
        $coupons = MerchantCoupon::find()->where(['merchant_id' => $merchant_id])->all();

        $response = ['coupons' => $this->getCouponJson($coupons)];

        return json_encode($response);
    }

    /**
     * @param $coupons
     * @return array
     */
    private function getCouponJson($coupons)
    {
        $list = [];
        if ($coupons) {
            /** @var UserCoupon | MerchantCoupon $coupon */
            foreach ($coupons as $coupon) {
                $list[] = [
                    'title' => $coupon->title,
                    'code' => $coupon->code
                ];
            }
        }
        return $list;
    }
}
